// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mock_trace_service.proto

package mocktrace

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	v2 "google.golang.org/genproto/googleapis/devtools/cloudtrace/v2"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Next available id: 2
type ListSpansResponse struct {
	Spans                []*v2.Span `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListSpansResponse) Reset()         { *m = ListSpansResponse{} }
func (m *ListSpansResponse) String() string { return proto.CompactTextString(m) }
func (*ListSpansResponse) ProtoMessage()    {}
func (*ListSpansResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_819c37506e2b5275, []int{0}
}

func (m *ListSpansResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSpansResponse.Unmarshal(m, b)
}
func (m *ListSpansResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSpansResponse.Marshal(b, m, deterministic)
}
func (m *ListSpansResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSpansResponse.Merge(m, src)
}
func (m *ListSpansResponse) XXX_Size() int {
	return xxx_messageInfo_ListSpansResponse.Size(m)
}
func (m *ListSpansResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSpansResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSpansResponse proto.InternalMessageInfo

func (m *ListSpansResponse) GetSpans() []*v2.Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

func init() {
	proto.RegisterType((*ListSpansResponse)(nil), "api.ListSpansResponse")
}

func init() {
	proto.RegisterFile("mock_trace_service.proto", fileDescriptor_819c37506e2b5275)
}

var fileDescriptor_819c37506e2b5275 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xbf, 0x4b, 0x03, 0x31,
	0x14, 0xc7, 0x95, 0xa2, 0x60, 0x5c, 0xf4, 0x86, 0x52, 0xea, 0x22, 0x75, 0xd1, 0xe1, 0x5e, 0xe0,
	0x9c, 0x44, 0x04, 0x29, 0xb8, 0xa9, 0x60, 0xeb, 0xe4, 0x52, 0x72, 0xe9, 0xf3, 0x0c, 0xbd, 0xcb,
	0x7b, 0x24, 0xb9, 0x03, 0xff, 0x7b, 0x49, 0xd2, 0xd3, 0xc1, 0xed, 0x25, 0xef, 0xfb, 0xe3, 0x93,
	0x88, 0x59, 0x47, 0x7a, 0xb7, 0x09, 0x4e, 0x69, 0xdc, 0x78, 0x74, 0x83, 0xd1, 0x08, 0xec, 0x28,
	0x50, 0x31, 0x51, 0x6c, 0xe6, 0x37, 0x0d, 0x51, 0xd3, 0xa2, 0xdc, 0xe2, 0x10, 0x88, 0x5a, 0x2f,
	0x75, 0x4b, 0xfd, 0x36, 0xc9, 0xe5, 0x50, 0xc9, 0x34, 0x64, 0xfd, 0xfc, 0x62, 0x2f, 0x4d, 0xa7,
	0xba, 0xff, 0x94, 0xd8, 0x71, 0xf8, 0xce, 0xcb, 0xc5, 0xab, 0x38, 0x7f, 0x36, 0x3e, 0xac, 0x59,
	0x59, 0xbf, 0x42, 0xcf, 0x64, 0x3d, 0x16, 0x77, 0xe2, 0xc8, 0xc7, 0x8b, 0xd9, 0xe1, 0xe5, 0xe4,
	0xfa, 0xb4, 0xba, 0x82, 0x9c, 0x00, 0x63, 0x19, 0xfc, 0x95, 0xc1, 0x50, 0x41, 0x34, 0xaf, 0xb2,
	0xa3, 0x7a, 0x13, 0x67, 0x2f, 0xa4, 0x77, 0xef, 0x71, 0xb7, 0xce, 0xd8, 0xc5, 0x83, 0x38, 0xf9,
	0xed, 0x28, 0xa6, 0x63, 0xd8, 0x88, 0x03, 0x4f, 0x11, 0x67, 0x3e, 0x05, 0xc5, 0x06, 0xfe, 0xb1,
	0x2c, 0x0e, 0x96, 0xcb, 0x8f, 0xc7, 0xc6, 0x84, 0xaf, 0xbe, 0x06, 0x4d, 0x9d, 0xcc, 0x6e, 0x63,
	0x03, 0x3a, 0xbb, 0x7f, 0x75, 0x49, 0x8c, 0x4e, 0x05, 0x43, 0xd6, 0x97, 0x8a, 0x4d, 0x19, 0x7f,
	0x4e, 0x2a, 0x36, 0xf7, 0x71, 0x48, 0x94, 0xf5, 0x71, 0x6a, 0xbb, 0xfd, 0x09, 0x00, 0x00, 0xff,
	0xff, 0xad, 0x7f, 0x91, 0xc8, 0x56, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MockTraceServiceClient is the client API for MockTraceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MockTraceServiceClient interface {
	ListSpans(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListSpansResponse, error)
}

type mockTraceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMockTraceServiceClient(cc grpc.ClientConnInterface) MockTraceServiceClient {
	return &mockTraceServiceClient{cc}
}

func (c *mockTraceServiceClient) ListSpans(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListSpansResponse, error) {
	out := new(ListSpansResponse)
	err := c.cc.Invoke(ctx, "/api.MockTraceService/ListSpans", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MockTraceServiceServer is the server API for MockTraceService service.
type MockTraceServiceServer interface {
	ListSpans(context.Context, *empty.Empty) (*ListSpansResponse, error)
}

// UnimplementedMockTraceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMockTraceServiceServer struct {
}

func (*UnimplementedMockTraceServiceServer) ListSpans(ctx context.Context, req *empty.Empty) (*ListSpansResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSpans not implemented")
}

func RegisterMockTraceServiceServer(s *grpc.Server, srv MockTraceServiceServer) {
	s.RegisterService(&_MockTraceService_serviceDesc, srv)
}

func _MockTraceService_ListSpans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockTraceServiceServer).ListSpans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MockTraceService/ListSpans",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockTraceServiceServer).ListSpans(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MockTraceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MockTraceService",
	HandlerType: (*MockTraceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSpans",
			Handler:    _MockTraceService_ListSpans_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mock_trace_service.proto",
}
